name: CI/CD

on:
  push:
    branches:
      - main

env:
  THEME_HTML: elegant
  THEME_PDF: kendall

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install JSON Resume themes
        run: npm install jsonresume-theme-${{ env.THEME_HTML }} jsonresume-theme-${{ env.THEME_PDF }}

      - name: Generate JSON
        run: npx @justingaffney/resume-renderer -i resume.yaml -o resume.json -f json

      - name: Validate resume.json
        run: npx resumed validate

      - name: Generate Markdown
        run: npx resume-renderer -i resume.json -o resume.md -f md

      - name: Generate HTML
        run: npx resume-renderer -i resume.json -o resume.html -f html --theme ${{ env.THEME_HTML }}

      - name: Generate PDF
        run: npx resume-renderer -i resume.json -o resume.pdf -f pdf --theme ${{ env.THEME_PDF }}

      - name: Generate DOCX
        run: npx resume-renderer -i resume.json -o resume.docx -f docx --theme ${{ env.THEME_PDF }}

      - name: Archive resume artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.*

# TODO Deploy job. For release branches create release, update resume.json Gist, and deploy GitHub Pages to https://resume.justingaffney.dev
