name: CI/CD

on:
  push:
    branches:
      - main

env:
  THEME_HTML: elegant
  THEME_PDF: kendall

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install resume CLI
        run: npm install resumed

      - name: Install resume theme
        run: npm install jsonresume-theme-${{ env.THEME_HTML }} jsonresume-theme-${{ env.THEME_PDF }}

      - name: Generate JSON
        uses: mikefarah/yq@master
        with:
          cmd: yq -p yaml -o json resume.yaml > resume.json

      - name: Validate resume.json
        run: npx resumed validate

      - name: Generate HTML
        run: |
          npx resumed render resume.json -t jsonresume-theme-${{ env.THEME_HTML }} -o resume.html
          mkdir pdf_input
          npx resumed render resume.json -t jsonresume-theme-${{ env.THEME_PDF }} -o pdf_input/index.html

      - name: Generate PDF
        uses: ferdinandkeller/html-to-pdf-action@v1
        with:
          source-path: pdf_input
          destination-path: resume.pdf

      - name: Archive resume artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.*

# TODO Deploy job. For release branches create release, update resume.json Gist, and deploy GitHub Pages to https://resume.justingaffney.dev
