name: Render resume

on:
    push:
      branches:
        - main

jobs:

  convert-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert resume from YAML to JSON
        uses: mikefarah/yq@master
        with:
          cmd: yq -p yaml -o json resume.yml > resume.json
      
      - name: Archive resume JSON
        uses: actions/upload-artifact@v4
        with:
          name: resume.json
          path: resume.json

  validate:
    runs-on: ubuntu-latest
    needs: convert-to-json
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install resumed
        run: npm install resumed

  render:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Render to HTML
        run: npx resumed resume.json -t jsonresume-theme-stackoverflow -o resume.html

      - name: Archive resume
        uses: actions/upload-artifact@v4
        with:
          name: resume.html
          path: resume.html
