name: Generate resume artifacts

on:
  push:
    branches:
      - main

env:
  THEME: elegant

jobs:

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install resume CLI
        run: npm install resumed

      - name: Install resume theme
        run: npm install jsonresume-theme-${{ env.THEME }}

      - name: Generate JSON
        uses: mikefarah/yq@master
        with:
          cmd: yq -p yaml -o json resume.yaml > resume.json

      - name: Validate resume.json
        run: npx resumed validate

      - name: Generate HTML
        run: npx resumed render resume.json -t jsonresume-theme-${{ env.THEME }} -o resume.html

      - name: Generate PDF
        run: |
          sudo apt install weasyprint 
          weasyprint resume.html resume.pdf

#      - name: Archive YAML
#        uses: actions/upload-artifact@v4
#        with:
#          name: resume.yaml
#          path: resume.yaml
#
#      - name: Archive JSON
#        uses: actions/upload-artifact@v4
#        with:
#          name: resume.json
#          path: resume.json
#
#      - name: Archive HTML
#        uses: actions/upload-artifact@v4
#        with:
#          name: resume.html
#          path: resume.html
#
#      - name: Archive PDF
#        uses: actions/upload-artifact@v4
#        with:
#          name: resume.pdf
#          path: resume.pdf

      - name: Archive resume artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.*

      # TODO Update resume.json Gist
